[package]

name = "hello_world"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[[bin]]

name = "pathfinder"
path = "src/main.rs"

[lib]
name = "roadsearch"
path = "src/lib.rs"