[package]

name = "pathsearch"
version = "0.0.1"
authors = [ "Osel <oselgithub@seznam.cz>" ]

[[bin]]
name = "pathfinder"
path = "src/main.rs"

[lib]
name = "roadsearch"
path = "src/lib.rs"

[dependencies]
getopts = "*"
